#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: F:\\sell.log
#  level:
#    com.wx.LoggerTest : debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.225:6536/wx_wxsell?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true
#   设置方言
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#   自动建表
    hibernate:
      ddl-auto: update

