#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: F:\\sell.log
#  level:
#    com.wx.LoggerTest : debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.225:6536/wx_wxsell?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true

    properties:
      hibernate:
        format  _sql: true
#   设置方言
#        dialect: org.hibernate.dialect.MySQL5Dialect
#   自动建表
    hibernate:
      ddl-auto: update

# 返回到前台的数据字段为null时不显示
  jackson:
    default-property-inclusion: non_null

# springboot 升级到2.0后 context-path 配置 不起作用
# context-path:
server:
  servlet:
    context-path: /wxsell

devtools:
  livereload:
    enabled: true #是否支持 livereload
    port: 35729
  restart:
    enabled: true #是否支持热部署

wechat:
  mpAppId: wx214031a92ee408b6
  mpAppSecret: dbb4bb1e7e210982d31ba6568c78347e

